---
- uid: 'fntp/carte_professionnelle_travaux_public'
  path: '/v3/fntp/unites_legales/{siren}/carte_professionnelle_travaux_publics'
  position: 290
  perimeter:
    entity_type_description: |+
      Toutes les **entreprises de travaux public** sont éligibles à demander une carte professionnelle à la FNTP.
      Au mois d'avril 2022, 7400 entreprises possédaient une carte professionnelle.

      ℹ️ Plus d'informations sur le [site de la FNTP](https://www.fntp.fr/outils/carte-professionnelle/tout-savoir-sur-la-carte-pro){:target="_blank"}
    entities:
      - entreprises
  call_id: "SIREN"
  providers:
    - 'fntp'
  keywords:
    - 'conformité'
    - 'conforme'
    - 'obligations'
    - 'cotisations'
    - 'btp'
    - 'bâtiment'
    - 'travaux'
    - 'decret janvier 2019'
    - 'marchés publics'
    - 'aides publiques'
    - 'fraude'
  data:
    description: |+
      Cette API délivre la carte professionnelle de travaux publics d'une entreprise, au format PDF, lorsque cette dernière est en règle de ses obligations sociales, administratives et juridiques.
  opening: public
  use_cases:
    - Marchés publics
  parameters:
    - Numéro de SIREN de l'entreprise
