---
- uid: 'infogreffe/mandataires_sociaux'
  path: '/v3/infogreffe/rcs/unites_legales/{siren}/mandataires_sociaux'
  position: 110
  perimeter:
    entity_type_description: |+
      Cette API concerne ✅ **toutes les entreprises inscrites au registre du commerce et des sociétés** (RCS).
      
      Il s'agit des entreprises ayant une activité commerciale. Pour plus de détails, consulter [le site du ministère de l'économie](https://www.economie.gouv.fr/entreprises/registre-commerce-societes-rcs){:target="_blank"}
    updating_rules_description: |+
      Les données sont **mises à jour en temps réel** avec les greffes. La donnée est donc la plus récente possible, _modulo_ le temps de saisie nécessaire pour les greffiers.
    entities:
      - entreprises
  call_id: "SIREN"
  providers:
    - 'infogreffe'
  keywords:
    - 'fonction'
    - 'nom'
    - 'prénom'
    - 'mandataire'
    - 'dirigeant'
    - 'date de naissance'
    - 'lieu de naissance'
    - 'actionnaire'
    - 'bénéficiare'
    - 'fraude'
  data:
    description: |+
      Cette API délivre **tous les mandataires sociaux  et leur fonction** au sein de l'entreprise&nbsp;:
      - S'il s'agit de personnes morales : le numéro de SIREN, la raison sociale et le nom du greffe seront précisés ;
      - S'il s'agit de personnes physiques : le nom, le prénom, la date de naissance, ainsi que le lieu de naissance de la personne physique seront indiqués.
  opening: protected
  use_cases:
    - Marchés publics
    - Aides publiques
    - Détection de la fraude
  parameters:
    - Numéro de SIREN de l'unité légale
