---
- uid: 'infogreffe/rcs/extrait'
  path: '/v3/infogreffe/rcs/unites_legales/{siren}/extrait_kbis'
  position: 115
  perimeter:
    entity_type_description: |+
      Cette API concerne ✅ **toutes les entreprises inscrites au registre du commerce et des sociétés (RCS)**.
      Il s'agit des entreprises ayant une activité commerciale. Pour plus de détails, consulter [le site du ministère de l'économie](https://www.economie.gouv.fr/entreprises/registre-commerce-societes-rcs){:target="_blank"}.
    updating_rules_description: |+
      Les données sont **mises à jour en temps réel avec les greffes**. La donnée est donc la plus récente possible, _modulo_ le temps de saisie nécessaire pour les greffiers.
    entities:
      - entreprises
  call_id: "SIREN"
  providers:
    - 'infogreffe'
  keywords:
    - 'decret janvier 2019'
    - 'kbis'
    - 'fusion'
    - 'redressement'
    - 'clotûre'
    - 'liquidation'
    - 'mandataire'
    - 'capital'
    - 'naf'
    - 'ape'
    - 'activité'
    - 'immatriculation'
  data:
    description: |+
      Cette API délivre :
      - un **extrait des données** présentes dans le registre du commerce et des sociétés. ⚠️ Il ne s’agit donc pas de la totalité des données présentes sur le Kbis mais d’une partie succincte ;
      - **tous les commentaires laissés par les greffiers**. Ces observations concernent, entre autres, les changements de capital, les transferts de siège, les fusions, les redressements et liquidations judiciaires (si la donnée est publique).
  opening: public
  use_cases:
    - Marchés publics
    - Aides publiques
    - Préremplissage d'un formulaire
    - Détection de la fraude
  parameters:
    - Numéro de SIREN de l'unité légale
