development:
  jwt_expiration_notice:
    cron: '0 1 * * *'
    class: 'JwtApiEntrepriseExpirationNoticeJob'
    queue: default

sandbox:
  jwt_expiration_notice:
    cron: '0 */4 * * *'
    class: 'JwtApiEntrepriseExpirationNoticeJob'
    queue: default

staging:
  jwt_expiration_notice:
    cron: '0 */4 * * *'
    class: 'JwtApiEntrepriseExpirationNoticeJob'
    queue: default

production:
  jwt_expiration_notice:
    cron: '0 */4 * * *'
    class: 'JwtApiEntrepriseExpirationNoticeJob'
    queue: default

  jwt_satisfaction_survey:
    cron: '0 3 * * *'
    class: 'AccessRequestSatisfactionSurveyJob'
    queue: default
